
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace GitHubIsusses_ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
            {
                SentimentText = @"==RUDE== Dude, you are rude upload that carl picture back, or else.",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = MLModel1.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Sentiment with predicted Sentiment from sample data...\n\n");


            Console.WriteLine($"SentimentText: {sampleData.SentimentText}");


            Console.WriteLine($"\n\nPredicted Sentiment: {predictionResult.Prediction}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
